name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
    steps:
      - uses: actions/checkout@v4
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: src

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
    steps:
      - uses: actions/deploy-pages@v1
