name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # If you need a build step (npm, Hugo, etc.), add it here.
      # For static files already in src/, we just upload the artifact.

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: src

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write # This is crucial for OIDC token access
    steps:
      - name: Configure Pages
        uses: actions/configure-pages@v4

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
